markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : drapergeek - dad
production_url : http://dad.drapergeek.com
description: "Small things I've discovered as a dad"
disqus_shortname: dad-drapergeek
analytics: UA-47166105-3
author :
  name : Jason Draper
  github : drapergeek
  twitter : drapergeek.
  email: jason@drapergeek.com
